### ISSUE TITLE
global.php

### ISSUE THREAD

**Issue by ovasclub** [php-fusion/PHP-Fusion-9-Locale#142]
13.setlocale(LC_TIME, "en_GB.utf8"); // Linux Server (Windows may differ)
13.setlocale(LC_**MESSAGES**, "ru_RU.UTF-8"); // Linux Server (Windows may differ)
Probably should be so?
13 setlocale(LC_TIME, "ru_RU.UTF-8"); // Linux Server (Windows may differ)

**Comment by RobiNN1** [comment]
Create pull request
