### ISSUE TITLE
New updated file ... admin/main.php

### ISSUE THREAD

**Issue by knapnet** [php-fusion/PHP-Fusion-9-Locale#3]
New updated file .... Italian / local / Italian / admin / main.php
In the short time I will translate other files and make corrections of the lyrics ...

Thanks for the Add to your workgroup PHP-Fusion 9 ...
I had sent the translation Premises in Hien and thank Domi-php to have carried Upload files ....
Unfortunately no admin rights and not easy to create or send files remotely all github ...

Happy New Year to all you ....

**Comment by Domi-php** [comment]
Thank you ,  Happy New Year!

**Comment by knapnet** [comment]
Thanks you, happy new year!
