### ISSUE TITLE
Theme Settings=>Форум<=Установка темы

### ISSUE THREAD

**Issue by ovas10** [php-fusion/PHP-Fusion-9-Locale#48]
main.php
45.$locale['S3'] = "Theme Settings";   (поменять форум на установка темы)
45.$locale['S3'] = "Установка темы";
global.php
239.$locale['global_171'] = "unique visits";
237.$locale['global_171'] = "уникальных посетителей" (поменять уникальных посетителей на посетителей на 06/03/2017)
237.$locale['global_171'] = "посетителей на "
/themes/Septenary/includes/components.php
```
if ($settings['visitorcounter_enabled']) {
echo "<p>".showcounter()."</p>\n";
```
=>
```
if ($settings['visitorcounter_enabled']) {
echo "<p>".showcounter()  .showsubdate()."</p>\n";
```

**Comment by rizado** [comment]
OK, I'll do it in some minutes.

**Comment by rizado** [comment]
@ovas10 , thanks for comments, this file was not updated some weeks.
Спасибо за замечания, этот файл не обновлялся несколько недель.

**Comment by rizado** [comment]
@ovas10 , I changed main.php file, thanks for you comment. But global_171 matches English version, I'll not change it before English locale
If you want to have modified theme create your own fork and change text in theme locale. Or create issue in main code repository.
Я изменил файл main.php, благодарю вас за замечание. Но значение global_171 соответствует английской версии, я не буду его менять до изменения английской локализации.
Если вы хотите иметь модифицированную под себя тему, создайте собственный форк и там меняйте текст в переводе темы. Или же создайте запрос на изменени темы в основном репозитории.
