### ISSUE TITLE
Error while entering Language settings in the new localization.

### ISSUE THREAD

**Issue by ovas10** [php-fusion/PHP-Fusion-9-Locale#82]
Error while entering Language settings in the new localization:
Fatal error: require_once(): Failed opening required '/home/ovasclub/public_html/locale/Russianuser_fields/user_aim.php' (include_path='.:/opt/alt/php71/usr/share/pear') in /home/ovasclub/public_html/locale/Russian/setup.php on line 315
![-2](https://cloud.githubusercontent.com/assets/16386011/25512143/5f9dfb32-2bed-11e7-9276-1d0faad3ab44.jpg)

In OpenServer  clean installation produces the same error:
![-2](https://cloud.githubusercontent.com/assets/16386011/25512854/94b1b11a-2bf2-11e7-89de-304c60fd1e4c.jpg)

**Comment by rizado** [comment]
> /Russianuser_fields
Where is a slash? It must be "Russian/user_fields".
Be sure that you use last version of sources.

**Comment by ovas10** [comment]
The new file setup.php is buggy, rolled back to the old one, everything switches. But if you do a clean installation in Russian, they both buggy. Checked in OpenServer

**Comment by rizado** [comment]
Try now, all work.
Tested at Jino hosting (Linux server).
