### ISSUE TITLE
Invalid display of poll start date in Russian localization

### ISSUE THREAD

**Issue by ovas10** [php-fusion/PHP-Fusion-9-Locale#90]
The problem of Russian localization
![-2](https://cloud.githubusercontent.com/assets/16386011/25688703/4782552e-30a3-11e7-8bae-28bf2ac66062.jpg)

**Comment by rizado** [comment]
Please show error log entries.

**Comment by ovas10** [comment]
Undefined index: global_123
Строка: 62 Файл -- themes/templates/admin_header.php
На странице -- infusions/member_poll_panel/poll_admin.php?aid=fc80dbc1ff41e77f&section=poll_vote  Создано Пользователь-Уровень: -103 -- IP-адрес: 2.132.106.69  Вкл. 04/06/2017
Отметить как
Новая


Исходный код (Строка: 52 - 72)
52	if ($settings['bootstrap'] || defined('BOOTSTRAP')) {
53	    define('BOOTSTRAPPED', TRUE);
54	    $bootstrap_theme_css_src = INCLUDES."bootstrap/bootstrap.min.css";
55	    add_to_footer("<script type='text/javascript' src='".INCLUDES."bootstrap/bootstrap.min.js'></script>");
56	    add_to_footer("<script type='text/javascript' src='".INCLUDES."bootstrap/holder.min.js'></script>");
57	}
58	
59	ob_start();
60	
61	@list($title) = dbarraynum(dbquery("SELECT admin_title FROM ".DB_ADMIN." WHERE admin_link=:base_url", array(':base_url' => FUSION_SELF)));
62	\PHPFusion\OutputHandler::setTitle($GLOBALS['locale']['global_123'].$GLOBALS['locale']['global_201'].($title ?
    $title.$GLOBALS['locale']['global_201'] : ""));
 Line 62 -- 10 минут назад
Undefined index: global_123
63	
64	// If the user is not logged in as admin then don't parse the administration page
65	// otherwise it could result in bypass of the admin password and one could do
66	// changes to the system settings without even being logged into Admin Panel.
67	// After relogin the user can simply click back in browser and their input will
68	// still be there so nothing is lost
69	if (!check_admin_pass('')) {
70	
71	    // If not admin, also must check if user_id is exist due to session time out.
72	    $user_id = fusion_get_userdata("user_id");
73
